<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'product','action'=>'update','id'=>$this->entity['id'])); ?>" method="post" enctype="multipart/form-data">
<fieldset>
<legend>Edit</legend>

    <?php $element = 'description'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <textarea type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>"><?php echo $this->form->get($element)->getValue(); ?></textarea>
        </div>
    </div>

    <?php $element = 'price'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>


    <?php if(!empty($this->entity['image_name'])): ?>
    <div class="control-group">
        <label class="control-label" for="<?php echo $element; ?>">Thumb</label>
        <div class="controls">
            <img src="<?php echo $this->basePath($this->entity['image_path'] . 'thumb/' . $this->entity['image_name']); ?>" />
        </div>
    </div>
    <?php endif; ?>

    <div class="control-group">
        <label class="control-label">Parameter</label>
        <div class="controls">
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" <?php if ($this->entity['hide']) echo 'checked="checked"' ?> />
                Hide
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="comment">
                <input type="checkbox" name="comment" id="comment" <?php if ($this->entity['comment']) echo 'checked="checked"' ?> />
                Comment
            </label>
        </div>
    </div>


    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Edit</button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'index')); ?>">
            Back
        </a>
    </div>
</fieldset>
</form>
