<style>
    th {
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -ms-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -o-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        line-height: 12px;text-shadow: white 0px 1px 0px;font-size: 12px;background-color:#dedede;color:#5E6469;
        border: solid 1px #cdcdcd;
        padding: 0;
    }
    th a {
        text-decoration: none;
        color:#5E6469;
    }
    th a:hover {
        text-decoration: none;
    }
</style>

<script type="text/javascript">
function checkAll(field)
{
    var elements = document.getElementsByName(field);
    for (i = 0; i < elements.length; i++)
	elements[i].checked = !elements[i].checked ;
}
</script>

<div class="form-actions" style="padding:0;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;">
    <form class="form-search" action="" method="post">
        <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'devis','action'=>'new')); ?>">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('New'); ?>
        </a>
        <div style="padding-left: 20px;" class="input-append">
            <input type="text" class="search-query">
            <button type="submit" class="btn"><i class="icon-search"></i></button>
        </div>
    </form>
</div>

<table class="table table-striped">
   
    <?php /* ?>
    <thead>
        <tr>
        <?php foreach($this->columns as $title=>$value): ?>
            <th><?php echo $value->getName(); ?></th>
        <?php endforeach; ?>
        </tr>
    </thead>
    <?php */ ?>
    
    <?php $thead=false; ?>
    <?php foreach($this->entities as $entity): ?>
    <?php if($thead==false): ?>
        <thead>
            <tr>
            <th><a href="?order=id&amp;sort=ASC">id</a><a></a></th>
            <th><a href="?order=username&amp;sort=ASC">username</a><a></a></th>
            <th><a href="?order=count&amp;sort=ASC">count</a><a></a></th>
            <th><a href="?order=price&amp;sort=ASC">price</a><a></a></th>
            <th><a href="?order=created&amp;sort=ASC">created</a><a></a></th>
            <th><a href="?order=payment&amp;sort=ASC">payment</a><a></a></th>
            <th><a href="?order=hide&amp;sort=ASC">hide</a><a></a></th>
            <th><input type="checkbox" name="action" onclick="javascript:checkAll('action[]')"></th>
            </tr>
        </thead>
        <tbody>
    <?php $thead=true; ?>
    <?php endif; ?>
        <tr>
            <td><a href='<?php echo $this->url('admin', array('controller'=>'devis','action'=>'edit', 'id'=>$entity['id'])); ?>'><?php echo $entity['id']; ?></a></td>
            <td><a href='<?php echo $this->url('admin', array('controller'=>'user','action'=>'edit', 'id'=>$entity['user_id'])); ?>'><?php echo $entity['firstname']; ?> <?php echo $entity['username']; ?></a></td>
            <td><?php echo $entity['count']; ?></td>
            <td><?php echo $entity['price']; ?></td>
            <td><?php echo date('d/m/Y H:i',$entity['created']); ?></td>
            <td><?php echo $entity['payment']; ?></td>
            <td><?php echo $entity['hide']; ?></td>
        <?php /*
        <?php $first = false; ?>
        <?php foreach($entity as $title=>$value): ?>
            <td>
                <?php
                if($first==false){echo "<a href='" . $this->url('admin', array('controller'=>'devis','action'=>'show', 'id'=>$entity['id'])) . "'>";}
                if ($title=='created') echo date('d/m/Y H:i',$value);
                elseif ($title=='username') echo "<a href='" . $this->url('admin', array('controller'=>'user','action'=>'edit', 'id'=>$entity['user_id'])) . "'>{$entity['username']}</a>";
                else echo $value; 
                if($first==false){echo "</a>";$first=true;}
               ?>
            </td>
        <?php endforeach; ?>
        */ ?>
            <td><input type="checkbox" name="action[]" value="<?php echo $entity['id']; ?>" /></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

    <div class="input-append" style="float:right">
        <select>
            <option>Delete</option>
        </select>
        <button class="btn" type="submit">Valider</button>
    </div>

    <div class="pagination">
        <ul>
            <li><a href="?page=<?php echo $this->page; ?>&move=prev&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">&lt;</a></li>
            <?php if($this->page<4): ?>
                <?php for($i=1;$i<6;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php else: ?>
                <?php for($i=$this->page-2;$i<$this->page+3;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php endif; ?>
            <li><a href="?page=<?php echo $this->page; ?>&move=next&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">&gt;</a></li>
        </ul>
    </div>