<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'devis','action'=>'create')); ?>" method="post" enctype="multipart/form-data">
<fieldset>
<legend>Create a Bill</legend>

    <?php $element = 'description'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <textarea type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>"><?php echo $this->form->get($element)->getValue(); ?></textarea>
        </div>
    </div>

    <?php $element = 'price'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <label class="checkbox" for="payment">
                <input type="checkbox" name="payment" id="hide" value="<?php echo $this->entity['hide']; ?>" />
                Payment
            </label>
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" value="<?php echo $this->entity['hide']; ?>" />
                Hide
            </label>
        </div>
    </div>

    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Create</button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'devis','action'=>'index')); ?>">
            Back
        </a>
    </div>
</fieldset>
</form>
