<script type="text/javascript">
function checkAll(field)
{
    var elements = document.getElementsByName(field);
    for (i = 0; i < elements.length; i++)
	elements[i].checked = !elements[i].checked ;
}
</script>
<style>
    th {
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -ms-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -o-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        line-height: 12px;text-shadow: white 0px 1px 0px;font-size: 12px;background-color:#dedede;
        color:#5E6469;
        border: solid 1px #cdcdcd;
        padding: 0;
    }
    ul {
        margin: 0;
        margin-top : 1em;
    }
    li {
        list-style-type:none;
    }
</style>

<?php
    echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
    echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
    echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<form class="form-search" method="post" action="<?php echo $this->url('admin', array('controller'=>'user','action'=>'index')); ?>">

<div class="form-actions" style="padding:10px;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;">
        <a class="btn btn-primary" href="<?php echo $this->url($this->module, array('controller'=>'user','action'=>'new')); ?>">
            <i class="icon-plus icon-white"></i>
        </a>
        
        <div style="padding-left: 20px;" class="input-append">
            <input type="text" name="query" class="search-query" value="<?php echo $this->query; ?>" />
            <button type="submit" class="btn"><i class="icon-search"></i></button>
        </div>
</div>
    
    <div><?php echo $this->count; ?> utilisateur(s)</div>
    
<table class="table table-striped">
    <thead>
        <tr>
            <th><a href="?order=id&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> ID</a></th>
            <th><a href="?order=username&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> Nom</a></th>
            <th><a href="?order=firstname&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> Prénom</a></th>
            <th><a href="?order=email&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> Email</a></th>
            <th><a href="?order=role_name&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> Profil</a></th>
            <th><a href="?order=updated&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> Dernière connexion</a></th>
            <th><a href="?order=is_active&amp;sort=<?php echo ($this->sort=='ASC') ? 'DESC' : 'ASC'; ?>"><i class="icon-arrow-down"></i> Actif</a></th>
            <th><input type="checkbox" name="action" onclick="javascript:checkAll('action[]')" /></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->entities as $entity): ?>
        <tr>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'user', 'action'=>'edit', 'id'=>$entity['id']), null, true); ?>"><?php echo $entity['id']; ?></a></td>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'user', 'action'=>'edit', 'id'=>$entity['id']), null, true); ?>"><?php echo $entity['username']; ?></a></td>
            <td><?php echo $entity['firstname']; ?></td>
            <td><?php echo $entity['email']; ?></td>
            <td><?php echo $entity['role_name']; ?></th>
            <td><?php echo date('d/m/Y H:s', $entity['updated']); ?></td>
            <td><?php if ($entity['is_active']): ?><i class="icon-ok"></i><?php else:  ?><i class="icon-minus-sign"></i><?php endif; ?></td>
            <td><input type="checkbox" name="action[]" value="<?php echo $entity['id']; ?>" /></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

    <div class="input-append" style="float:right">
        <select name="action_select">
            <option value="delete"><?php echo $this->translate('Delete'); ?></option>
        </select>
        <button name="action_submit" class="btn" type="submit" value="1"><?php echo $this->translate('Submit'); ?></button>
    </div>
        
    <div class="pagination">
        <ul>
            <li><a href="?page=<?php echo $this->page; ?>&move=prev&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">&lt;</a></li>
            <?php if($this->page<4): ?>
                <?php for($i=1;$i<6;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php else: ?>
                <?php for($i=$this->page-2;$i<$this->page+3;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php endif; ?>
            <li><a href="?page=<?php echo $this->page; ?>&move=next&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">&gt;</a></li>
        </ul>
    </div>

</form>