<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

    <div class="well">
        <strong>Profil</strong>
    </div>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'user', 'action'=>'profil', 'id' => $this->entity['id'] )); ?>" method="post" autocomplete="off">
    

    
    <fieldset>

        <div class="control-group">
            <label class="control-label" for="firstname">Firstname</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="firstname" name="firstname" value="<?php echo $this->entity['firstname']; ?>">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="firstname">Lastname</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="username" name="username" value="<?php echo $this->entity['username']; ?>">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="phone">Phone</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="phone" name="phone" value="<?php echo $this->entity['phone']; ?>">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="email">Email</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="email" name="email" value="<?php echo $this->entity['email']; ?>">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="city">City</label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="city" name="city" value="<?php echo $this->entity['city']; ?>">
            </div>
        </div>
        
    </fieldset>

    <div class="well">
        <button class="btn btn-primary" type="submit">
            <i class="icon-pencil icon-white"></i>
            Editer
        </button>
    </div>

    <div class="control-group">
            <label class="control-label" for="oldPassword">Old Password</label>
            <div class="controls">
                <input type="password" class="input-xlarge" id="oldPassword" name="oldPassword">
                <p class="help-block">Require only if you want to change your password.</p>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="password">New Password</label>
            <div class="controls">
                <input type="password" class="input-xlarge" id="password" name="password">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="confirmPassword">Confirm Password</label>
            <div class="controls">
                <input type="password" class="input-xlarge" id="confirmPassword" name="confirmPassword">
                <p class="help-block">Retype the new password.</p>
            </div>
        </div>
    
    <div class="well">
        <button class="btn btn-primary" type="submit">
            <i class="icon-pencil icon-white"></i>
            Change Password
        </button>
    </div>
    
    <?php echo $this->formInput($this->form->get('csrf')); ?>
    
</form>