<h2>Newsletter</h2>

<form method="post" action="<?php echo $this->url('index', array('controller'=>'newsletter','action'=>'valid')); ?>">
    <input type="hidden" name="organization" value="www.breizhadonf.com" />
    <p><input type="text" placeholder="email" name="email"></p>
    <p><input type="checkbox" name="partner" checked="checked" /> Recevoir les informations des partenaires</p>
    <p><input class="btn" type="submit" value="Envoyer"></p>
</form>