<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'project','action'=>'create')); ?>" method="post">
<fieldset>
<legend>Create a Project</legend>

    <?php $element = 'name'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'description'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <textarea type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>"><?php echo $this->form->get($element)->getValue(); ?></textarea>
        </div>
    </div>

    <?php $element = 'keywords'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'banner'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'footer'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'subtitle'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Parameter</label>
        <div class="controls">
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" value="<?php echo $this->entity['hide']; ?>" />
                Hide
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="comment">
                <input type="checkbox" name="comment" id="comment" value="<?php echo $this->entity['comment']; ?>" />
                Comment
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="menu">
                <input type="checkbox" name="menu" id="menu" value="<?php echo $this->entity['menu']; ?>" />
                Menu
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="hits">
                <input type="checkbox" name="hits" id="hits" value="<?php echo $this->entity['hits']; ?>" />
                Hits
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="contact">
                <input type="checkbox" name="contact" id="contact" value="<?php echo $this->entity['contact']; ?>" />
                Contact
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="config">
                <input type="checkbox" name="config" id="config" value="<?php echo $this->entity['config']; ?>" />
                Config
            </label>
        </div>

        <div class="controls">
            <label class="checkbox" for="log">
                <input type="checkbox" name="log" id="log" value="<?php echo $this->entity['log']; ?>" />
                Log
            </label>
        </div>
    </div>

    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Create</button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'project','action'=>'index'), null, true); ?>">
            Back
        </a>
    </div>
</fieldset>
</form>
