
    <div class="alert alert-success">
    <h4 class="alert-heading">Thank you!</h4>
    You successfully send this message.
    </div>

    <div class="well">
        <p>Name : <?php echo $this->name; ?></p>
        <p>Email : <?php echo $this->email; ?></p>
        <p>Message : <?php echo $this->message; ?></p>
        <?php if(isset($this->copy)): ?><p>A copy is send to <?php echo $this->email; ?></p><?php endif; ?>
    </div>

    <div class="form-actions">
        <a class="btn" href="<?php echo $this->url('home'); ?>">
            Back
        </a>
    </div>