<form method="post" action="<?php echo $this->url('admin', array('controller' => 'delivery', 'action' => 'create')); ?>">
    
    <?php foreach($this->form as $element): ?>
        <?php if($element->getAttribute('type')!='hidden' and $element->getAttribute('type')!='submit' and $element->getName()!='delivery_id'): ?>
            <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
                <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
                <div class="controls">

                    <?php echo $element->getValue(); ?>   

                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php echo $this->formInput($this->form->get('csrf')); ?>
    <button type="submit" class="btn btn-primary">
        <i class="icon-plus icon-white"></i>
        <?php echo $this->translate('New'); ?>
    </button>
</form>