<style>
    th {
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -ms-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -o-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        line-height: 12px;text-shadow: white 0px 1px 0px;font-size: 12px;background-color:#dedede;color:#5E6469;
        border: solid 1px #cdcdcd;
        padding: 0;
    }
</style>

<form class="form-search" method="post" action="<?php echo $this->url('admin', array('controller'=>'mail','action'=>'index')); ?>">

<div class="form-actions" style="padding:10px;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;">
        <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'mail','action'=>'new')); ?>">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('Message'); ?>
        </a>
        <div style="padding-left: 20px;" class="input-append">
            <input type="text" class="search-query" name="query">
            <button type="submit" class="btn"><i class="icon-search"></i></button>
        </div>
    </form>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->entities as $entity): ?>
        <tr>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'mail','action'=>'show', 'id'=>$entity['id'])); ?>"><?php echo $entity['name']; ?></a></td>
            <td><?php echo date('d-m-Y H:i',$entity['created']); ?></td>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'user', 'action'=>'edit', 'id'=>$entity['id']), null, true); ?>"><?php echo $entity['author'] ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="pagination">
  <ul>
    <li><a href="{{ path('_topic_list',{page:previous}) }}">&lt;</a></li>
    <li class="active">
      <a href="{{ path('_topic_list',{page:1}) }}">1</a>
    </li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="{{ path('_topic_list',{page:next}) }}">&gt;</a></li>
  </ul>
</div>