<div class="well">
    <textarea></textarea>
</div>

<form action="<?php echo $this->url('admin', array('controller'=>'topic','action'=>'create')); ?>" method="post">
<fieldset>
<legend>Response</legend>


    <?php echo $this->form->csrf; ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">
            Save
        </button>
        <a class="btn" href="{{ path('user') }}">
            List
        </a>
    </div>

</fieldset>
</form>