<form action="" method="post">
    <div>
	<input type="text" />
        <button class="btn" type="submit">Search</button>
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Link</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->services as $service): ?>
        <tr>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'service','action'=>'edit', 'id'=>$service['id'])); ?>"><?php echo $service['name']; ?></a></td>
            <td><?php echo $service['url'] ?></td>
            <td><?php echo date('d-m-Y H:i',$service['created']); ?></td>
            <td><?php echo date('d-m-Y H:i',$service['updated']); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="form-actions">
    <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'service','action'=>'new')); ?>">
        <i class="icon-plus icon-white"></i>
        Link
    </a>
    <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'index','action'=>'index')); ?>">
        Back
    </a>
</div>