<table class="table table-striped">
	<?php foreach($this->statistics as $key=>$value): ?>
	<tr>
		<th><?php echo $key; ?></th>
		<td><?php echo $value; ?></td>
	</tr>
	<?php endforeach; ?>
</table>

<table class="table table-striped">
	<tr>
		<th>Status</th>
		<th>Name</th>
		<th>Expediteur</th>
		<th>Destinataire</th>
		<th>Subject</th>
		<th>Date</th>
	</tr>
	<?php foreach($this->messages as $item): ?>
		<tr>
			<td>
				<span class="label
				<?php if($item->status=='sent'): ?>
					label-success
				<?php elseif($item->status=='queued'): ?>
					label-warning
				<?php elseif($item->status=='spam'): ?>
					label-important
				<?php elseif($item->status=='opened'): ?>
					label-info
				<?php elseif($item->status=='clicked'): ?>
					label-primary
				<?php elseif($item->status=='blocked'): ?>
					label-inverse
				<?php endif; ?>
				"><?php echo $item->status; ?></span>
			</td>
			<td><?php echo $item->from_name; ?></td>
			<td><?php echo $item->from_email; ?></td>
			<td><?php echo $item->email; ?></td>
			<td><?php echo $item->subject; ?></td>
			<td><?php echo date('d/m/Y H:i',$item->sendtime_start); ?></td>
		</tr>
	<?php endforeach; ?>
</table>