<table class="table table-striped">
<?php foreach($this->stats as $key=>$stat): ?>
    <tr>
        <td><?php echo $key; ?></th>
        <td><?php echo $stat; ?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php /*
<table class="table table-striped">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Choices</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->entities as $entity): ?>
        <tr>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'shopattributechoice','action'=>'index', 'id'=>$entity['sa_id'])); ?>"><?php echo $entity['sa_name']; ?></a></td>
            <td><?php echo $entity['count']; ?></td>
            <td><?php echo date('d-m-Y H:i',$entity['created']); ?></td>
            <td><?php echo date('d-m-Y H:i',$entity['updated']); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<form method="post" action="<?php echo $this->url('admin', array('controller'=>'shopattribute','action'=>'index')); ?>">
    <button type="submit" class="btn btn-primary">
        Update
    </button>
</form>
*/ ?>