<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'product','action'=>'update','id'=>$this->entity['id'])); ?>" method="post" enctype="multipart/form-data">
<fieldset>
<legend>Edit a Product</legend>

    <div class="control-group">
        <label class="control-label" for="topic">Menu</label>
        <div class="controls">
        <select name="parent" id="parent">
            <option value="0" selected="selected" />
            <?php foreach($this->topics as $topic): ?>
                <option <?php if($this->entity['topic_id']==$topic['id']): ?>selected="selected"<?php endif; ?> value="<?php echo $topic['id']; ?>"><?php echo $topic['name']; ?></option>
            <?php endforeach; ?>
        </select>
        </div>
    </div>


    <?php $element = 'name'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'description'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <textarea type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element ?>"><?php echo $this->entity[$element]; ?></textarea>
        </div>
    </div>

    <?php $element = 'stock'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'weight'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'price'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'file'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="file" name="<?php echo $element; ?>" id="<?php echo $element; ?>" />
        </div>
    </div>

    <?php if(!empty($this->entity['image_name'])): ?>
    <div class="control-group">
        <label class="control-label" for="<?php echo $element; ?>">Thumb</label>
        <div class="controls">
            <img src="<?php echo $this->basePath($this->entity['image_path'] . 'thumb/' . $this->entity['image_name']); ?>" />
        </div>
    </div>
    <?php endif; ?>

    <div class="control-group">
        <label class="control-label">Parameter</label>
        <div class="controls">
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" <?php if ($this->entity['hide']) echo 'checked="checked"' ?> />
                Hide
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="comment">
                <input type="checkbox" name="comment" id="comment" <?php if ($this->entity['comment']) echo 'checked="checked"' ?> />
                Comment
            </label>
        </div>
    </div>

    <h3>Déclinaisons</h3>

    <?php $title = null; ?>
    
    <?php foreach($this->options as $option): ?>
    <?php if($title!=$option['name']): ?>
        <?php if($title!=null): ?></div></div><?php endif; ?>
        <?php $title = $option['name']; ?>
        <div class="control-group" style="border:solid 1px #dedede;border-radius: 10px;padding:10px;">
            <label class="control-label" for="<?php echo $element; ?>">
                <input style="width:100px;" type="text" value="<?php echo $option['name']; ?>" />
            </label>
            <div class="controls">
        <?php endif; ?>
            <div>
                <input type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="option" value="<?php echo $option['option_name']; ?>" />
                <input type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="stock" value="<?php echo $option['stock']; ?>" />
            </div>
    <?php endforeach; ?>
    <?php if($title!=null): ?></div></div><?php endif; ?>
    
    <?php $element = 'option'; ?>
    <div style="margin-bottom: 1em;">
        Nom : <input name="options[1]" type="text" value="" placeholder="Déclinaison 1" />
    </div>
    <div style="border:solid 1px #dedede;border-radius: 10px;padding:10px;">
        <table>
            <tr>
                <th>Option</th>
                <th>Stock variable</th>
                <th>Modification du prix</th>
                <th>Montant</th>
            </tr>
            <tr>
                <td><input name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Option" /></td>
                <td><input value="<?php echo $this->entity['stock']; ?>" name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Stock" /></td>
                <td>
                    <select><option>Ne change pas</option><option>Egal à</option><option>Augmente de</option><option>Réduire de</option></select>
                </td>
                <td>
                    <input value="<?php echo $this->entity['price']; ?>" name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Prix" />
                </td>
            </tr>
        </table>

    </div>
    
    <div style="margin-bottom: 1em;margin-top: 1em;">
        Nom : <input name="options[1]" type="text" value="" placeholder="Déclinaison 1" />
    </div>
    <div style="border:solid 1px #dedede;border-radius: 10px;padding:10px;">
        <table>
            <tr>
                <th>Option</th>
                <th>Stock</th>
                <th>Prix</th>
            </tr>
            <tr>
                <td><input name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Option" /></td>
                <td><input value="<?php echo $this->entity['stock']; ?>" name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Stock" /></td>
                <td>
                    <select><option>Egal à</option><option>Augmente de</option><option>Réduire de</option></select>
                    <input value="<?php echo $this->entity['price']; ?>" name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Prix" />
                </td>
            </tr>
        </table>

    </div>

<h3>Stocks</h3>

    <div style="border:solid 1px #dedede;border-radius: 10px;padding:10px;">
        <table>
            <tr>
                <th>Option</th>
                <th>Stock</th>
                <th>Modification du prix</th>
                <th>Montant</th>
                <th>Prix</th>
            </tr>
            <tr>
                <td>Taille S, Logo Bleu</td>
                <td><input value="<?php echo $this->entity['stock']; ?>" name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Stock" /></td>
                <td>
                    <select><option>Ne change pas</option><option>Egal à</option><option>Augmente de</option><option>Réduire de</option></select>
                </td>
                <td>
                    <input value="<?php echo $this->entity['price']; ?>" name="options[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Prix" />
                </td>
                <td><?php echo $this->entity['price']; ?></td>
            </tr>
        </table>

    </div>

    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Edit</button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'ShopAttribute','action'=>'index')); ?>">
            Back
        </a>
    </div>
</fieldset>
</form>
