<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=374508785922632";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<?php echo $this->topic['content']; ?>

<div class="fb-comments" data-href="<?php echo $this->url('topicbyname',array('name'=>$topic['name'])); ?>" data-num-posts="10" data-width="800"></div>