<script type="text/javascript">
function checkAll(field)
{
    var elements = document.getElementsByName(field);
    for (i = 0; i < elements.length; i++)
	elements[i].checked = !elements[i].checked ;
}
</script>
<style>
    th {
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -ms-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -o-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        line-height: 12px;text-shadow: white 0px 1px 0px;font-size: 12px;background-color:#dedede;color:#5E6469;
        border: solid 1px #cdcdcd;
        padding: 0;
    }
    ul {
        margin: 0;
    }
    li {
        list-style-type:none;
    }
</style>

<?php
    echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
    echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
    echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<?php if ($this->upload_dir_exist == false): ?>
    <div class="alert alert-error">
        <strong>Error !</strong> Upload directory (public/upload/products) not exist.
    </div>
<?php endif; ?>

<div class="form-actions" style="padding:0;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;">
    <form class="form-search" action="" method="post">
        <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'new')); ?>">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('New'); ?>
        </a>
        <div style="padding-left: 20px;" class="input-append">
            <input type="text" name="query" class="search-query" value="<?php echo $this->query; ?>" />
            <button type="submit" class="btn"><i class="icon-search"></i></button>
        </div>
    </form>
</div>

<form name="product_form" method="post" action="<?php echo $this->url('admin', array('controller'=>'product','action'=>'delete')); ?>">

<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('Photo'); ?></th>
            <th><?php echo $this->translate('Name'); ?></th>
            <th><?php echo $this->translate('Stock'); ?></th>
            <th><?php echo $this->translate('Price'); ?></th>
            <th><?php echo $this->translate('Weight'); ?></th>
            <th><?php echo $this->translate('Last update'); ?></th>
            <th><?php echo $this->translate('Author'); ?></th>
            <th><input type="checkbox" name="action" onclick="javascript:checkAll('action[]')" /></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->entities as $entity): ?>
        <tr>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'edit', 'id'=>$entity['id'])); ?>"><img style="max-height:50px;" src="<?php echo $this->basePath($this->image_path . 'thumb/' . $entity['image_name']); ?>" /></a></td>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'edit', 'id'=>$entity['id'])); ?>"><?php if($entity['hide']): ?><s><?php endif; ?><?php echo $entity['name']; ?><?php if($entity['hide']): ?></s><?php endif; ?></a></td>
            <td><?php echo $entity['stock']; ?></td>
            <td><?php if(!empty($entity['price'])) echo number_format($entity['price'],2,'.',' '); ?></td>
            <td><?php echo $entity['weight']; ?></td>
            <td><?php echo date('d-m-Y H:i',$entity['updated']); ?></td>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'user', 'action'=>'edit', 'id'=>$entity['id'])); ?>"><?php echo $entity['author'] ?></a></td>
            <td><input type="checkbox" name="action[]" value="<?php echo $entity['id']; ?>" /></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

    <div class="input-append" style="float:right">
        <select>
            <option><?php echo $this->translate('Delete'); ?></option>
        </select>
        <button class="btn" type="submit"><?php echo $this->translate('Submit'); ?></button>
    </div>

	<div class="pagination">
        <ul>
            <li><a href="?page=<?php echo $this->page; ?>&move=prev&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><</a></li>
            <?php if($this->page<4): ?>
                <?php for($i=1;$i<6;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php else: ?>
                <?php for($i=$this->page-2;$i<$this->page+3;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php endif; ?>
            <li><a href="?page=<?php echo $this->page; ?>&move=next&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">></a></li>
        </ul>
    </div>
    
</form>
