<table class="table table-striped">
    <tr>
        <th>Sender</th>
        <td><?php echo $this->entity['name']; ?> ( <?php echo $this->entity['email']; ?> )</td>
    </tr>
    <tr>
        <th>Date</th>
        <td><?php echo date('d-m-Y H:i',$this->entity['updated']); ?></td>
    </tr>
</table>

<div class="well">
    <?php echo $this->entity['message']; ?>
</div>

    <div class="form-actions">
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'mail','action'=>'index')); ?>">
            List
        </a>
    </div>
    
<form action="<?php echo $this->url('admin', array('controller'=>'mail','action'=>'create', 'id' => $this->entity['id'])); ?>" method="post" {{ form_enctype(form) }}>
<fieldset>
<legend>Response</legend>

    <div class="control-group">
        <label class="control-label">Name</label>
        <div class="controls"><?php echo $this->user->username; ?></div>
    </div>

    <div class="control-group">
        <label class="control-label">Message</label>
        <div class="controls"><textarea></textarea></div>
    </div>

    <?php echo $this->form->csrf; ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">
            Send
        </button>
        <a class="btn" href="">
            Clear
        </a>
    </div>

</fieldset>
</form>