<p>
        <label>id</label>
        <input name='id' type='text' value='<?php echo $entity['id']; ?>' />
</p>
<p>
        <label>bankorder_id</label>
        <input name='bankorder_id' type='text' value='<?php echo $entity['bankorder_id']; ?>' />
</p>
<p>
        <label>product_id</label>
        <input name='product_id' type='text' value='<?php echo $entity['product_id']; ?>' />
</p>
<p>
        <label>user_id</label>
        <input name='user_id' type='text' value='<?php echo $entity['user_id']; ?>' />
</p>
<p>
        <label>value</label>
        <input name='value' type='text' value='<?php echo $entity['value']; ?>' />
</p>
<p>
        <label>count</label>
        <input name='count' type='text' value='<?php echo $entity['count']; ?>' />
</p>
<p>
        <label>created</label>
        <input name='created' type='text' value='<?php echo $entity['created']; ?>' />
</p>
<p>
        <label>updated</label>
        <input name='updated' type='text' value='<?php echo $entity['updated']; ?>' />
</p>
<p>
        <label>hide</label>
        <input name='hide' type='text' value='<?php echo $entity['hide']; ?>' />
</p>
<p>
        <label>payment</label>
        <input name='payment' type='text' value='<?php echo $entity['payment']; ?>' />
</p>

<table style="width:100%" class="table table-striped">

    <tr>
        <th style="width: 50%;">Articles</th>
        <th>Quantité</th>
        <th>Prix unitaire</th>
        <th>Total</th>
    </tr>
        
    <?php
    if (count($this->baskets)>0):
    foreach($this->baskets as $entity):
    ?>
        <tr>
            <td>
            <img style="border:solid 1px #dedede;border-radius:10px;margin-right: 10px;max-height: 6em;float: left;" src="<?php echo $this->basePath($entity['image_path'] . 'thumb/' . $entity['image_name']); ?>" />
            <a href="<?php echo $this->url('index', array('controller'=>'product','action'=>'show','id'=>$entity['product_id'])); ?>"><?php echo $entity['name']; ?></a><br />
                <?php foreach(json_decode($entity['attributes']) as $key=>$attribute): ?>
                    <b><?php echo $key; ?></b>
                    <?php echo $attribute; ?>
                <?php endforeach; ?>
            </td>
            <td>
                <?php echo $entity['count']; ?>
            </td>
            <td><?php echo $entity['price']; ?> &euro;</td>
            <td><?php echo $entity['price']*$entity['count']; ?> &euro;</td>
        </tr>
    <?php endforeach;endif; ?>

    <tr>
        <td></td>
        <td></td>
        <td>Frais de port</td>
        <td style="font-weight:bold;">
            <?php echo $this->transport; ?> &euro;
            (<?php $kg = $this->weight/1000; echo $kg; ?>kg)
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
        </td>
        <td><b>Total</b></td>
        <td style="font-weight:bold;"><?php $total = $this->price + $transport; echo $this->total; ?> &euro;</td>
    </tr>
    </table>

<form method="post" action="">
    <button type="submit" class="btn btn-primary">
        <i class="icon-plus icon-white"></i>
        Ajouter une commande
    </button>
</form>