<?php
/*
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
    }
    echo '</div>';
}*/
?>

<form method="post" action="<?php echo $this->url('admin', array('controller'=>'css','action'=>'index'), null, true); ?>">

<div class="form-actions">
    <button class="btn btn-primary" type="submit">
        Save
    </button>
    <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'design','action'=>'index')); ?>">
        Back
    </a>
</div>
    
    <textarea name="css" id="css" style="width: 100%;height: 400px;"><?php echo $this->project['css']; ?></textarea>
    
        <?php echo $this->formInput($form->get('csrf')); ?>
<div class="form-actions">
    <button class="btn btn-primary" type="submit">
        Save
    </button>
    <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'design','action'=>'index')); ?>">
        Back
    </a>
</div>
    
</form>