<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'product','action'=>'create')); ?>" method="post" enctype="multipart/form-data">
<fieldset>
    <legend>New Product</legend>

    <div class="control-group">
        <label class="control-label" for="topic">Menu</label>
        <div class="controls">
        <select name="parent" id="parent">
            <option value="0" selected="selected" />
            <?php foreach($this->topics as $topic): ?>
                <option <?php if($this->entity['topic_id']==$topic['id']): ?>selected="selected"<?php endif; ?> value="<?php echo $topic['id']; ?>">
                    <?php for($i=0;$i<$topic['depth'];$i++): ?> - <?php endfor; ?> <?php echo $topic['name']; ?>
                </option>
            <?php endforeach; ?>
        </select>
            <a href="<?php echo $this->url('admin', array('controller'=>'topic','action'=>'new')); ?>" class="btn">Ajouter menu</a>
        </div>
    </div>

    <?php $element = 'name'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'description'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <textarea type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>"><?php echo $this->form->get($element)->getValue(); ?></textarea>
        </div>
    </div>

    <?php $element = 'stock'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'weight'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'price'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
        </div>
    </div>

    <?php $element = 'file'; ?>
    <div class="control-group<?php if (count($this->form->get($element)->getMessages()) > 0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="file" name="<?php echo $element; ?>[]" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Parameter</label>
        <div class="controls">
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" value="<?php echo $this->entity['hide']; ?>" />
                Hide
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="comment">
                <input type="checkbox" name="comment" id="comment" value="<?php echo $this->entity['comment']; ?>" />
                Comment
            </label>
        </div>
    </div>

    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('New'); ?>
        </button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'index')); ?>">
            <?php echo $this->translate('Back'); ?>
        </a>
    </div>
</fieldset>
</form>
