<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form method="post" action="<?php echo $this->url('admin', array('controller' => 'acl', 'action' => 'update', 'id'=> $entity['role_id'])); ?>">
    
    <?php foreach($this->form as $element): ?>
        <?php if($element->getAttribute('type')!='hidden' and $element->getAttribute('type')!='submit' and $element->getName()!='role_id'): ?>
            <div class="control-group input-prepend input-append<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
                <label class="control-label add-on" style="font-weight: bold;" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>

                    <?php echo $this->formElement($element); ?>   

            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <div>
        <select>
            <?php foreach($this->allows as $allow): ?>
            <option><?php echo $allow['resource_name']; ?></option>
            <?php endforeach; ?>
        </select>
        <button class="btn">Add</button>
    </div>

    
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th><?php echo $this->translate('Name'); ?></th>
                <th><input type="checkbox" name="action" onclick="javascript:checkAll('action[]')" /></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->resources as $resource): ?>
            <tr>
                <td><input type="checkbox" name="action[]" value="<?php echo $resource['role_id']; ?>" /></td>
                <td><a href="<?php echo $this->url('admin', array('controller'=>'acl','action'=>'edit', 'id'=>$resource['role_id'])); ?>"><?php echo $resource['resource_name']; ?></a></td>
                <td><input type="checkbox" name="action[]" value="<?php echo $resource['role_id']; ?>" /></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    
    <div class="input-append" style="float:right">
        <select>
            <option>Delete</option>
        </select>
        <button class="btn" type="submit">Valider</button>
    </div>
        
    <div class="pagination">
        <ul>
            <li><a href="">Prev</a></li>
            <li class="active">
                <a href="">1</a>
            </li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="">Next</a></li>
        </ul>
    </div>


    <?php echo $this->formInput($this->form->get('csrf')); ?>
    <button type="submit" class="btn btn-primary">
        <?php echo $this->translate('Edit'); ?>
    </button>
    <a class="btn" href="<?php echo $this->url('admin', array('controller' => 'acl', 'action' => 'index')); ?>">Cancel</a>
</form>