<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form method="post" action="<?php echo $this->url('admin', array('controller' => 'acl', 'action' => 'create')); ?>">
    
    <?php foreach($this->form as $element): ?>
        <?php if($element->getAttribute('type')!='hidden' and $element->getAttribute('type')!='submit' and $element->getName()!='delivery_id'): ?>
            <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
                <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
                <div class="controls">

                    <?php echo $this->formElement($element); ?>   

                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php echo $this->formInput($this->form->get('csrf')); ?>
    <button type="submit" class="btn btn-primary">
        <i class="icon-plus icon-white"></i>
        <?php echo $this->translate('New'); ?>
    </button>
</form>