<?php

foreach ($this->form->getMessages() as $key => $errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach ($errors as $error) {
        echo $error;
    }
    echo '</div>';
}
if (isset($this->errors)) {
    foreach ($this->errors as $key => $error) {
        echo '<div class="alert alert-error">';
        echo '<h4 class="alert-heading">';
        echo $key;
        echo '</h4>';
        echo $error;
        echo '</div>';
    }
}
?>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/plupload/plupload.full.min.js'); ?>"></script>

<script type="text/javascript">
$(function() {
    var uploader = new plupload.Uploader({
        runtimes : 'html5',
        browse_button : 'pickfiles',
        container : 'plupload',
        max_file_size : '10mb',
        url : '<?php echo $this->url('admin', array('controller' => 'document', 'action' => 'upload')); ?>',
        filters : [
            {title : "Image files", extensions : "jpg,gif,png"},
            {title : "Zip files", extensions : "zip"}
        ],
        resize : {width : 320, height : 240, quality : 90}
    });
    uploader.bind('Init', function(up, params) {
        $('#filelist').html("<div></div>");
        $('#alternative_upload').css('display','none');
        $('#plupload').css('display','block');
    });
    $('#uploadfiles').click(function(e) {
        uploader.start();
        e.preventDefault();
    });
    uploader.init();
    uploader.bind('FilesAdded', function(up, files) {
        $.each(files, function(i, file) {
            $('#filelist').append(
                '<div id="' + file.id + '">' +
                file.name + ' (' + plupload.formatSize(file.size) + ') <b></b>' +
            '</div>');
        });
        up.refresh(); // Reposition Flash/Silverlight
    });
    uploader.bind('UploadProgress', function(up, file) {
        $('#' + file.id + " b").html(file.percent + "%");
    });
    uploader.bind('Error', function(up, err) {
        $('#filelist').append("<div>Error: " + err.code +
            ", Message: " + err.message +
            (err.file ? ", File: " + err.file.name : "") +
            "</div>"
        );
        up.refresh();
    });
    uploader.bind('FileUploaded', function(up, file) {
        $('#' + file.id + " b").html("100%");
    });
});
</script>

<div id="plupload" class="well" style="display:none;">
    <a id="pickfiles" href="#" class="btn">Add files</a>
    <a id="uploadfiles" href="#" class="btn btn-primary">Upload</a>
    <div id="filelist">No runtime found.</div>
</div>

<form id="alternative_upload" class="form-horizontal well" style="clear:both;padding:0;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;" action="<?php echo $this->url('admin', array('controller' => 'document', 'action' => 'index')); ?>" method="post" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->formInput($this->form->get('document_csrf')); ?>
        <input type="hidden" name="subdir" value="<?php echo $this->subdir; ?>" />
        <?php if ($this->uploadDirExit == false): ?>
            <div class="alert alert-error">
                <strong>Error !</strong> Upload directory not exist.
            </div>
        <?php endif; ?>

        <div class="control-group">
            <label class="control-label" for="document">Fichier :</label>
            <div class="controls"><input type="file" name="document" id="document" /><button class="btn btn-primary" type="submit">Upload</button></div>
        </div>
    </fieldset>
</form>


    <?php foreach ($this->listFiles as $key => $file): ?>
    <form class="form-horizontal" action="<?php echo $this->url('admin', array('controller' => 'document', 'action' => 'do')); ?>" method="post">
        
        <div style="clear:both">
            <div style="float:left;margin-bottom:10px;margin-right:10px;width:80px;height:80px;text-align: center;">
                <input type="hidden" name="subdir" value="<?php echo $this->subdir; ?>" />
                <?php if(is_dir(ROOT_PATH . '/public/uploads/' . $this->layout()->project['id'] . '/' . $this->subdir . '/' . $file)): ?>
                    <a href="<?php echo $this->url('admin', array('controller' => 'document', 'action' => 'index', 'id' => $file)); ?>">
                        <img src="<?php echo $this->basePath('/themes/default/img/admin/folder.png'); ?>" style="border-radius: 10px;max-width:80px;" />
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->basePath('uploads/' . $this->layout()->project['id'] . '/' . $file); ?>">
                        <img class="img-polaroid" src="<?php echo $this->basePath('uploads/' . $this->layout()->project['id'] . '/' . $file); ?>" style="max-width:80px;" />
                    </a>
                <?php endif; ?>
            </div>
            <div class="well" style="margin-left: 100px">
                <div>
                    <?php if (!empty($this->size[$key])) echo $this->size[$key].'ko'; ?> 
                </div>
                <div class="input-append">
                    <a class="btn" href="<?php echo $this->basePath('uploads/' . $this->layout()->project['id'] . '/' . $file); ?>"><i class="icon-zoom-out"></i></a>
                    <input type="text" name="rename-text" value="<?php echo $file; ?>" />
                    <button type="submit" class="btn" name="rename" value="<?php echo $file; ?>">
                        Rename
                    </button>
                    <button type="submit" class="btn btn-danger" name="delete" value="<?php echo $file; ?>"><i class="icon-trash icon-white"></i></button>
                    <?php if(!is_dir(ROOT_PATH . '/public/uploads/' . $this->layout()->project['id'] . '/' . $this->subdir . '/' . $file)): ?>
                        <a class="btn" href="<?php echo $this->url('image_show', array('path'=> $file)); ?>">Edit</a>
                    <?php endif; ?>
                </div>
                <?php $slash =  (!empty($this->subdir)) ? '/' : '' ?>
                <div><?php echo $this->serverUrl() . $slash . $this->subdir . $this->basePath('uploads/' . $this->layout()->project['id'] . '/' . $file); ?></div>
            </div>
        </div>
    </form>
    <?php endforeach; ?>

<div style="clear:both"></div>

<?php
foreach ($this->form_dir->getMessages() as $key => $errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach ($errors as $error) {
        echo $error;
    }
    echo '</div>';
}
?>

<form class="form-horizontal form-actions" action="<?php echo $this->url('admin', array('controller' => 'document', 'action' => 'index')); ?>" method="post">

        <div class="input-append">
        <input type="hidden" name="subdir" value="<?php echo $this->subdir; ?>" />
        <input placeholder="New directory" type="text" name="directory" id="directory" />
        <button class="btn" type="submit">Create</button>
        </div>
        <?php echo $this->formInput($this->form_dir->get('dir_csrf')); ?>

</form>