<script type="text/javascript">
function checkAll(field)
{
    var elements = document.getElementsByName(field);
    for (i = 0; i < elements.length; i++)
	elements[i].checked = !elements[i].checked ;
}
</script>

<style>
    th {
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -ms-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -o-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        line-height: 12px;
        text-shadow: white 0px 1px 0px;
        font-size: 12px;
        background-color:#dedede;
        color:#5E6469;
        border: solid 1px #cdcdcd;
        padding: 0;
    }
</style>

<div class="row-fluid">
    <div class="span9">

<form class="form-search" action="<?php echo $this->url($this->module, array('controller'=>$this->controller,'action'=>'index')); ?>" method="post">
    
<div class="form-actions" style="padding:10px;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;">
        <a class="btn btn-primary" href="<?php echo $this->url($this->module, array('controller'=>$this->controller,'action'=>'new')); ?>">
            <i class="icon-plus icon-white"></i>
        </a>
        <span style="font-size:x-large;font-weight:normal;position:relative;top:5px;"><?php echo $this->title; ?></span>
</div>

<table class="table table-striped">
        <?php foreach($this->entities as $entity): ?>
        <?php if($this->thead==true): ?>
            <thead>
                <tr>
                <?php foreach($entity as $title=>$value): ?>
                    <?php if ($this->order==$title and $this->sort=='ASC') $sort='DESC'; else $sort='ASC'; ?>
                    <?php $element = $this->form->get($title); ?>
                    <th>
                        <a href="?order=<?php echo $title; ?>&sort=<?php echo $sort; ?>">
                            <?php echo $this->formLabel($element); ?>
                            <?php if ($this->order==$title and $this->sort=='ASC'): ?>
                                <i class="icon-arrow-down"></i>
                            <?php elseif($this->order==$title): ?>
                                <i class="icon-arrow-up"></i>
                            <?php endif; ?>
                        <a>
                    </th>
                <?php endforeach; ?>
                     <th><input type="checkbox" name="action" onclick="javascript:checkAll('action[]')" /></th>
                </tr>
            </thead>
            <tbody>
        <?php $this->thead=false; ?>
        <?php endif; ?>
        <tr>
            <?php foreach($entity as $title=>$value): ?>
                <td>
                    
                    <?php
                    if($title==$this->id){ echo "<a href='" . $this->url($this->module, array('controller'=>$this->controller,'action'=>'edit', 'id'=>$entity[$this->id])) . "'>";}
                    if ($title=='created') echo date('d/m/Y H:i',$value);
                    elseif ($title=='updated') echo date('d/m/Y H:i',$value);
                    else echo $value; 
                    if($title==$this->id){echo "</a>";}
                   ?>
                </td>
            <?php endforeach; ?>
            <td><input type="checkbox" name="action[]" value="<?php echo $entity[$this->id]; ?>" /></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

    <div class="input-append" style="float:right">
        <select name="action_select">
            <option value="delete"><?php echo $this->translate('Delete'); ?></option>
        </select>
        <button name="action_submit" class="btn" type="submit" value="1"><?php echo $this->translate('Submit'); ?></button>
    </div>
        
    <div class="pagination">
        <ul>
            <li><a href="?page=<?php echo $this->page; ?>&move=prev&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">&lt;</a></li>
            <?php if($this->page<4): ?>
                <?php for($i=1;$i<6;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php else: ?>
                <?php for($i=$this->page-2;$i<$this->page+3;$i++): ?>
                    <li<?php if($i==$this->page): ?> class="active"<?php endif; ?>><a href="?page=<?php echo $i; ?>&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>"><?php echo $i; ?></a></li>
                <?php endfor; ?>
            <?php endif; ?>
            <li><a href="?page=<?php echo $this->page; ?>&move=next&order=<?php echo $this->order; ?>&sort=<?php echo $this->sort; ?>">&gt;</a></li>
        </ul>
    </div>

</form>
</div>
<div class="span3">
    <form action="<?php echo $this->url($this->module, array('controller'=>$this->controller,'action'=>'index')); ?>" method="post">
        <?php foreach($this->form as $element): ?>  
            <?php if($element->getAttribute('type')!='hidden' and $element->getAttribute('type')!='submit'): ?>
            <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
                <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
                <div class="controls">
                    <?php echo $this->formElement($element); ?>   
                </div>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <div><input type="submit" class="btn" name="search_submit" value="Rechercher"></div>
    </form>
</div>
</div>