<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <title>AppyShop Admin</title>
        <link rel="shortcut icon" href="<?php echo $this->basePath('favicon.ico'); ?>" />
        <meta name="description" content="Appydo Administration">
        <meta name="keywords" content="Appydo Administration">
        <meta name="generator" content="Appydo CMS" />
        <meta name="author" content="Appydo">
        <meta name="robots" content="no-robots" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Le styles -->
        <link href="<?php echo $this->basePath('themes/default/css/bootstrap.min.css'); ?>" rel="stylesheet" />
        <style type="text/css">
        body {
            font-size: 13px;
            padding-top: 60px;
            padding-bottom: 40px;
        }
        body, input, textarea, p {
            color: #373737 !important;
            font: 15px "Helvetica Neue", Helvetica, Arial, sans-serif !important;
            font-weight: 300 !important;
            line-height: 1.625 !important;
        }
        .btn {
            font-size: 13px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }
        .page-header h1 {
            font-size: medium;
            font-weight: normal;
        }
        option[selected] { background: white; }
        </style>
        <link href="<?php echo $this->basePath('themes/default/css/bootstrap-responsive.min.css'); ?>" rel="stylesheet">

        <!-- Le fav and touch icons -->
        <link rel="alternate" 
          type="application/rss+xml" 
          title="RSS" 
          href="/rss/rss?id=${global?.id}&amp;name=${global?.name}" />
        <link rel="shortcut icon" href="/public/images/favicon.ico">
        <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
        <script type="text/javascript" src="<?php echo $this->basePath('/themes/default/js/jquery-1.8.3.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('/themes/default/js/bootstrap.min.js'); ?>"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="dropdown">
                      <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->layout()->project['name'] ;?> <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <?php foreach($this->layout()->projects as $project): ?>
                            <li>
                                <a tabindex="-1" href="<?php echo $this->url('admin', array('controller'=>'project','action'=>'index')); ?>?select=<?php echo $project['id']; ?>">
                                    <?php echo $project['name'] ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                      </ul>
                    </li>
                        <li class="active"><a href="<?php echo $this->url('admin', array('action'=>'index')); ?>"><i class="icon-home"></i> <?php echo $this->translate('Dashboard'); ?></a></li>
                            <li><a href="<?php echo $this->url('preview',array('project'=>$this->layout()->project['name'])); ?>"><i class="icon-search"></i> <?php echo $this->translate('Voir le site'); ?></a></li>
                        <?php if($this->user!=null): ?>
                            <li><a href="<?php echo $this->url('auth', array('action'=>'logout')); ?>"><i class="icon-off"></i> <?php echo $this->translate('Logout'); ?></a></li>
                        <?php else: ?>
                            <li><a href="">Login</a></li>
                            <li><a href="">Signup</a></li>
                        <?php endif;?>
                            <?php /*
                            <li><form style="margin-bottom:0;padding-top:5px;" class="form-search" action="" method="post">
                                <div class="input-append">
                                    <input type="text" class="search-query">
                                    <button type="submit" class="btn">Search</button>
                                </div>
                            </form></li> */ ?>
                    </ul>
                    
                    <?php if($this->user!=null): ?>
                    <p class="navbar-text pull-right">
                        <i class="icon-user"></i> <a href="<?php echo $this->url('admin', array('controller'=>'user','action'=>'profil')); ?>"><?php echo $user->firstname; ?> <?php echo $user->username; ?></a>
                    </p>
                    <?php endif;?>
                </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

    <div class="container-fluid" style="padding:0;margin:0;">
      <div class="row-fluid">
        <div class="span2">
          <div class="sidebar-nav  well">
            <ul class="nav nav-list">
                <?php /*
                <form style="margin: 0;overflow: hidden;" method="post" action="<?php echo $this->url('admin', array('controller'=>'project','action'=>'index')); ?>">
                    <select name="select" onchange="submit();" style="font-weight: bold;-webkit-appearance: none;border: 0;background: transparent;width: 80px;">
                        <?php foreach($this->layout()->projects as $project): ?>
                            <option <?php if($project['id']==$this->layout()->project['id']): ?>selected="selected"<?php endif; ?> style="border: 0;background: white;" value="<?php echo $project['id'] ?>"><?php echo $project['name'] ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input class="btn" type="submit" value="switch" />
                     
                </form>
                 * */ ?>
              <?php if($this->user!=null): ?>
              <?php //if (isset($project) and $project!=null): ?>
                <li class="nav-header"><?php echo $this->translate('Content'); ?></li>
                <li<?php if($this->controller=='Admin\Controller\Topic' and $this->action!='trash'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'topic', 'action'=>'index')); ?>"><i class="icon-file"></i> <?php echo $this->translate('Pages'); ?></a></li>
                <li<?php if($this->controller=='Admin\Controller\Comment'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'comment','action'=>'index')); ?>"><i class="icon-comment"></i> Comments</a></li>
                <li<?php if($this->controller=='Admin\Controller\Mail'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'mail', 'action'=>'index')); ?>"><i class="icon-envelope"></i> Messages</a></li>
                <li<?php if($this->controller=='Admin\Controller\Document'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'document', 'action'=>'index')); ?>"><i class="icon-download"></i> Files</a></li>
                <li<?php if($this->action=='trash'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'topic','action'=>'trash')); ?>"><i class="icon-trash"></i> Corbeille</a></li>
              
              <li class="nav-header"><?php echo $this->translate('Shop'); ?></li>
              <li<?php if($this->controller=='Admin\Controller\Product'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'index')); ?>"><i class="icon-th"></i> <?php echo $this->translate('Products'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Shopattribute'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'shopattribute','action'=>'index')); ?>"><i class="icon-tags"></i>  <?php echo $this->translate('Attributs'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Bill'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'bill','action'=>'index')); ?>"><i class="icon-shopping-cart"></i> <?php echo $this->translate('Bills'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Ship'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'ship','action'=>'index')); ?>"><i class="icon-shopping-cart"></i> <?php echo $this->translate('Commande'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Devis'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'devis','action'=>'index')); ?>"><i class="icon-barcode"></i> <?php echo $this->translate('Devis'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Delivery'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'delivery','action'=>'index')); ?>"><i class="icon-plane"></i> <?php echo $this->translate('Delivery'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Delay'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'delay','action'=>'index')); ?>"><i class="icon-time"></i> <?php echo $this->translate('Delay'); ?></a></li>
              
              <li<?php if($this->controller=='Admin\Controller\ProductImageResize'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'ProductImageResize','action'=>'index')); ?>"><i class="icon-th"></i> <?php echo $this->translate('Image size'); ?></a></li>

              <li class="nav-header">Options</li>
              <?php /*
              <li><a href="<?php echo $this->url('admin', array('controller'=>'index','action'=>'info')); ?>"><img src="<?php echo $this->basePath('/themes/default/img/admin/comments.png'); ?>" alt="Information" /> Information</a></li>
              */ ?>
              <li<?php if($this->controller=='Admin\Controller\Project' and $this->action=='edit'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'project','action'=>'edit', 'id'=>$this->layout()->project['id'])); ?>"><i class="icon-cog"></i> Parameter</a></li>
              <li<?php if($this->controller=='Admin\Controller\Contact'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'contact','action'=>'index')); ?>"><i class="icon-cog"></i> Contact</a></li>
              <?php if($this->layout()->role['role_name']=='admin'): ?>
                <li<?php if($this->controller=='Admin\Controller\Database'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'database','action'=>'index')); ?>"><i class="icon-hdd"></i> Database</a></li>
                
                <li<?php if($this->controller=='Admin\Controller\Translate'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'translate','action'=>'index')); ?>"><i class="icon-hdd"></i> Translate</a></li>
                <li<?php if($this->controller=='Admin\Controller\Design'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'design','action'=>'index')); ?>"><i class="icon-picture"></i> Design</a></li>
                <li<?php if($this->controller=='Admin\Controller\Log'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'log','action'=>'index')); ?>"><i class="icon-list"></i> Log</a></li>
                <li<?php if($this->controller=='Admin\Controller\EmailData'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'EmailData','action'=>'index')); ?>"><i class="icon-list"></i> Email</a></li>
                <li<?php if($this->controller=='Admin\Controller\Newsletter'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'Newsletter','action'=>'index')); ?>"><i class="icon-list"></i> Newsletter</a></li>
              <?php endif; ?>

              <li class="nav-header">Localisation</li>
              <li<?php if($this->controller=='Admin\Controller\Lang'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'lang','action'=>'index')); ?>"><i class="icon-picture"></i> Localisation</a></li>
              <li<?php if($this->controller=='Admin\Controller\Lang'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'lang','action'=>'index')); ?>"><i class="icon-picture"></i> Langue</a></li>
              <li<?php if($this->controller=='Admin\Controller\Lang'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'lang','action'=>'index')); ?>"><i class="icon-picture"></i> Zone</a></li>
              <li<?php if($this->controller=='Admin\Controller\Lang'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'lang','action'=>'index')); ?>"><i class="icon-picture"></i> Devise</a></li>
              <li<?php if($this->controller=='Admin\Controller\Tax'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'tax','action'=>'index')); ?>"><i class="icon-time"></i> <?php echo $this->translate('Tax'); ?></a></li>
              <li<?php if($this->controller=='Admin\Controller\Tax'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'tax','action'=>'index')); ?>"><i class="icon-time"></i> Traduction</a></li>
              
              <li class="nav-header">Utilisateur</li>
              <li<?php if($this->controller=='Admin\Controller\User' and $this->action=='profil'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'user','action'=>'profil')); ?>"><i class="icon-user"></i> Profil</a></li>
              <?php if($this->layout()->role['role_name']=='admin'): ?>
                <li<?php if($this->controller=='Admin\Controller\User'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'user','action'=>'index')); ?>"><i class="icon-certificate"></i> Membres</a></li>
                <li<?php if($this->controller=='Admin\Controller\Acl'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'acl','action'=>'index')); ?>"><i class="icon-lock"></i> Group</a></li>
                <li<?php if($this->controller=='Admin\Controller\Resource'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'resource','action'=>'index')); ?>"><i class="icon-lock"></i> Resource</a></li>
                <li<?php if($this->controller=='Admin\Controller\Privilege'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'privilege','action'=>'index')); ?>"><i class="icon-lock"></i> Privilege</a></li>
              <?php endif; ?>
              <?php /* <li><a href="<?php echo $this->url('auth', array('action'=>'logout')); ?>"><img src="<?php echo $this->basePath('/themes/default/img/admin/logout.png'); ?>" alt="logout" /> Déconnection</a></li> */ ?>
              <?php endif;?>
              
              <li class="nav-header">Modules</li>
              <li><a href="<?php echo $this->url('admin', array('controller'=>'mailjet','action'=>'index')); ?>"><i class="icon-star"></i> Mailjet</a></li>
              
              <li class="nav-header">Shortcuts</li>
              <?php
            		if(isset($this->services)):
            		foreach($this->services as $service):
              ?>
              <li><a href="<?php echo $service['url']; ?>"><i class="icon-star"></i> <?php echo $service['name']; ?></a></li>
              <?php endforeach;endif; ?>
              <li<?php if($this->controller=='Admin\Controller\Service'):?> class="active"<?php endif; ?>><a href="<?php echo $this->url('admin', array('controller'=>'service','action'=>'new')); ?>"><i class="icon-plus-sign"></i> Ajouter</a></li>
              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

        <div class="span10" style="padding:12px;margin:0;">
            <?php echo $this->layout()->content; ?>
        </div>
        </div>
        </div>
        <div style="font-size:90%;text-align:center;color:#707070;">
         2012/<?php echo date('Y'); ?> Copyright &copy; <a href="http://www.appydo.com">Appydo</a> - Tous droits réservés - <a href="https://github.com/Appydo/AppyCMS/issues">Bug Tracker</a>
         - <a href="http://www.appydo.com">Studio Appydo</a>
        </div>
</html>
