<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <title>AppyPage CMS</title>
        <link rel="shortcut icon" href="<?php echo $this->basePath('/favicon.ico'); ?>" />

        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="generator" content="AppyPage CMS" />
        <meta name="author" content="Appydo">
        <meta name="robots" content="all" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link href="<?php echo $this->basePath('/themes/default/css/bootstrap.min.css'); ?>" rel="stylesheet" />
        <style type="text/css">
            body {
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: #f5f5f5;
            }

            .form-signin {
                max-width: 300px;
                padding: 19px 29px 29px;
                margin: 0 auto 20px;
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin input[type="text"],
            .form-signin input[type="password"] {
                font-size: 16px;
                height: auto;
                margin-bottom: 15px;
                padding: 7px 9px;
            }
            .container {
                margin:auto;
            }
        </style>
        <link href="<?php echo $this->basePath('/themes/immobilier-en-reseau.fr/css/bootstrap-responsive.min.css'); ?>" rel="stylesheet">
    </head>
    
    <body>

        <div class="container">

            <?php echo $this->content; ?>

        </div>

    </body>
</html>