<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
    }
    echo '</div>';
}
?>

<form enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('module' => 'admin','controller'=>'service','action'=>'update'), null, true); ?>">
    
    <input type="hidden" name="id" id="id" value="<?php echo $this->entity['id']; ?>" />
    
    <div class="control-group">
        <label for="name">Name</label>
        <div class="controls"><input type="text" name="name" id="name" value="<?php echo $this->entity['name']; ?>" /></div>
    </div>
    
    <div class="control-group">
        <label for="name">Link</label>
        <div class="controls"><input type="text" name="link" id="link" value="<?php echo $this->entity['url']; ?>" /></div>
    </div>
    
    <div class="control-group">
        <label for="name">Type</label>
        <div class="controls"><input type="text" name="type" id="type" value="<?php echo $this->entity['type']; ?>" /></div>
    </div>
    
    <?php echo $this->formInput($this->form->get('service_csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Save</button>
        <a class="btn" href="<?php echo $this->url(array('module' => 'admin','controller'=>'service','action'=>'index'), 'default', true); ?>">
            List
        </a>
    </div>
</form>
