
    <div class="form-actions btn-group">
        <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'project','action'=>'new'), null, true); ?>">
            <i class="icon-plus icon-white"></i>
            Project
        </a>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'index','action'=>'index')); ?>">
            Back
        </a>
    </div>

    <form action="<?php echo $this->url('admin', array('controller'=>'project','action'=>'index')); ?>" method="post">
        <?php foreach($this->projects as $item): ?>
        <div class="well">
            <div class="input-append">
                <button class="btn btn-primary<?php if($this->current==$item['id']): ?> disabled<?php endif; ?>" name="select" value="<?php echo $item['id']; ?>"><i class="icon-chevron-down icon-white"></i></button>
                <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'project','action'=>'index', 'project'=>$item['name'])); ?>"><i class="icon-zoom-out"></i></a>
                <input <?php // if($this->layout()->project['theme']==$design): ?> readonly<?php // endif; ?> type="text" name="rename-text" value="<?php echo $item['name']; ?>" />
                <?php /*
                <button type="submit" class="btn<?php if($this->layout()->project['theme']==$design): ?> disabled<?php endif; ?>" name="rename" value="<?php echo $file; ?>">
                    Rename
                </button>
                 * 
                 */ ?>
                <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'project','action'=>'edit', 'id'=>$item['id'])); ?>"><i class="icon-pencil"></i></a>
                <a class="btn btn-danger<?php if($this->layout()->project['theme']==$design): ?> disabled<?php endif; ?>" href=""><i class="icon-trash icon-white"></i></a>
            </div>
            <p><?php echo $item['description']; ?></p>
            <p>Hits : <?php echo $item['hits']; ?></p>
        </div>
        <?php endforeach; ?>
    </form>