<script type="text/javascript">
function checkAll(field)
{
    var elements = document.getElementsByName(field);
    for (i = 0; i < elements.length; i++)
	elements[i].checked = !elements[i].checked ;
}
</script>

<style>
    th {
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -ms-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        -o-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px white inset;
        line-height: 12px;text-shadow: white 0px 1px 0px;font-size: 12px;background-color:#dedede;
        color:#5E6469;
        border: solid 1px #cdcdcd;
        padding: 0;
    }
    ul {
        margin: 0;
    }
    li {
        list-style-type:none;
    }
</style>

<?php
    echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
    echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
    echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<div class="form-actions" style="padding:0;margin:0;padding-top:10px;margin-bottom:10px;padding-left:10px;">
    <form class="form-search" action="" method="post">
        <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>$this->controller,'action'=>'new')); ?>">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('New'); ?>
        </a>
        <div style="padding-left: 20px;" class="input-append">
            <input type="text" class="search-query">
            <button type="submit" class="btn"><i class="icon-search"></i></button>
        </div>
    </form>
</div>

<form method="post" action="<?php echo $this->url('admin', array('controller'=>$this->controller,'action'=>'delete')); ?>">


<table class="table table-striped">

        <?php foreach($this->entities as $entity): ?>
        <?php if($this->thead==false): ?>
            <thead>
                <tr>
                <?php foreach($entity as $title=>$value): ?>
                    <?php if($title!='pir_id'): ?>
                        <th><a href="?order=<?php echo $title; ?>&sort=ASC"><?php echo $title; ?><a></th>
                    <?php endif; ?>
                <?php endforeach; ?>
                     <th><input type="checkbox" name="action" onclick="javascript:checkAll('action[]')" /></th>
                </tr>
            </thead>
            <tbody>
        <?php $this->thead=true; ?>
        <?php endif; ?>
        <tr>
            <?php foreach($entity as $title=>$value): ?>
                <?php if($title!='pir_id'): ?>
                <td>
                    <?php
                    if($title=='name'){echo "<a href='" . $this->url('admin', array('controller'=>$this->controller,'action'=>'edit', 'id'=>$entity[$this->id])) . "'>";}
                    if ($title=='created') echo date('d/m/Y H:i',$value);
                    elseif ($title=='updated') echo date('d/m/Y H:i',$value);
                    elseif ($title=='active') {
                        echo (!$value) ? '<i class="icon-ok"></i>' : '<i class="icon-minus-sign"></i>';
                    }
                    else echo $value; 
                    if($title=='name'){echo "</a>";}
                   ?>
                </td>
                <?php endif; ?>
            <?php endforeach; ?>
            <td><input type="checkbox" name="action[]" value="<?php echo $entity[$this->id]; ?>" /></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

    <div class="input-append" style="float:right">
        <select>
            <option><?php echo $this->translate('Delete'); ?></option>
        </select>
        <button class="btn" type="submit">Valider</button>
    </div>
        
    <div class="pagination">
        <ul>
            <li><a href="">&lt;</a></li>
            <li class="active">
                <a href="">1</a>
            </li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="">&gt;</a></li>
        </ul>
    </div>

</form>