<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<!-- Load jQuery -->
<link type="text/css" href="<?php echo $this->basePath('/css/ui-lightness/jquery-ui-1.8.21.custom.css'); ?>" rel="stylesheet" />    

<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-1.7.2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.8.21.custom.min.js'); ?>"></script>

<!-- Load TinyMCE -->
<script type="text/javascript" src="<?php echo $this->basePath('/js/tinymce/jquery.tinymce.min.js') ?>"></script>
<script type="text/javascript">
    $().ready(function() {
            $('.add').click(function() {
                $('textarea').tinymce().execCommand('mceInsertContent',false,'<img src="'+this.href+'" />');
                return false;
            });
            $( "#dialog" ).dialog({ autoOpen: false });
            $('#box').click(function() {$('#dialog').dialog('open')});
            $('textarea').tinymce({
                // Location of TinyMCE script
                script_url : '<?php echo $this->basePath('/js/tinymce/tinymce.min.js') ?>',
                remove_script_host : false,
                convert_urls : false,
                height : "300",
                width  : "100%",
                menu : {},
                plugins: [
                    "advlist autolink lists link image charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen",
                    "insertdatetime media table contextmenu paste textcolor emoticons"
                ],
                toolbar: "undo redo | styleselect fontselect fontsizeselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | code preview fullscreen | searchreplace insertdatetime table print charmap visualblocks anchor removeformat | forecolor backcolor emoticons",
                /*
                // General options
                theme : "advanced",
                plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

                // Theme options
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect,charmap,emotions",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,print",
                theme_advanced_resizing : true,
                /*
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,
                */
                theme_advanced_statusbar_location : "none",
                // Example content CSS (should be your site CSS)
                // content_css : "css/content.css",

                // Drop lists for link/image/media/template dialogs
                template_external_list_url : "lists/template_list.js",
                external_link_list_url : "lists/link_list.js",
                external_image_list_url : "lists/image_list.js",
                media_external_list_url : "lists/media_list.js",
                schema: "html5",
                // Replace values for the template plugin
                template_replace_values : {
                        username : "Some User",
                        staffid : "991234"
                }
            });
    });
</script>
<!-- /TinyMCE -->

<form method="post" action="<?php echo $this->url('admin', array('controller' => 'EmailData', 'action' => 'create')); ?>">
    
    <div class="control-group input-prepend input-append">
        <span class="add-on" style="font-weight: bold;">Title</span>
        <?php $element = $this->form->get('ed_title'); ?>
        <?php echo $this->formElement($element); ?>   
        <a class="btn" href="#" id="box"><i class="icon-picture"></i> Insert images</a>
    </div>

    <?php $element = $this->form->get('ed_content'); ?>
    <?php echo $this->formElement($element); ?>  

        <input type="hidden" name="ed_hide" value="0" /> 
    <div style="margin-top: 1em;margin-bottom: 1em;">
        <select name="lang_id">
            <?php foreach($this->langs as $lang): ?>
                <option value="<?php echo $lang['lang_id']; ?>"><?php echo $lang['lang_value']; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php echo $this->formInput($this->form->get('csrf')); ?>
    
    <div class="form-actions" style="padding:0;margin:0;padding:10px;margin-bottom:10px;">
        <button class="btn btn-primary" type="submit">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('New'); ?>
        </button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'EmailData','action'=>'index')); ?>">
            <?php echo $this->translate('Back'); ?>
        </a>
    </div>

</form>