<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<!-- Load jQuery -->
<link type="text/css" href="<?php echo $this->basePath('/css/ui-lightness/jquery-ui-1.8.21.custom.css'); ?>" rel="stylesheet" />    

<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-1.7.2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.8.21.custom.min.js'); ?>"></script>

<!-- Load TinyMCE -->
<script type="text/javascript" src="<?php echo $this->basePath('/js/tiny_mce/jquery.tinymce.js') ?>"></script>
<script type="text/javascript">
    $().ready(function() {
            $('.add').click(function() {
                $('textarea').tinymce().execCommand('mceInsertContent',false,'<img src="'+this.href+'" />');
                return false;
            });
            $( "#dialog" ).dialog({ autoOpen: false });
            $('#box').click(function() {$('#dialog').dialog('open')});
            $('textarea').tinymce({
                // Location of TinyMCE script
                script_url : '<?php echo $this->basePath('/js/tiny_mce/tiny_mce.js') ?>',
                remove_script_host : false,
                convert_urls : false,
                height : "300",
                width  : "100%",

                // General options
                theme : "advanced",
                plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

                // Theme options
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect,charmap,emotions",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,print",
                theme_advanced_resizing : true,
                /*
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,
                */
                theme_advanced_statusbar_location : "none",
                // Example content CSS (should be your site CSS)
                // content_css : "css/content.css",

                // Drop lists for link/image/media/template dialogs
                template_external_list_url : "lists/template_list.js",
                external_link_list_url : "lists/link_list.js",
                external_image_list_url : "lists/image_list.js",
                media_external_list_url : "lists/media_list.js",
                schema: "html5",
                // Replace values for the template plugin
                template_replace_values : {
                        username : "Some User",
                        staffid : "991234"
                }
            });
    });
</script>
<!-- /TinyMCE -->

<form method="post" action="<?php echo $this->url($this->module, array('controller' => $this->controller, 'action' => 'update', 'id'=> $entity[$this->id])); ?>">
    
    <?php $element = $this->form->get('newsletter_title'); ?>
    <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
        <div class="controls">
            <?php echo $this->formElement($element); ?>   
        </div>
    </div>

    <?php $element = $this->form->get('newsletter_email'); ?>
    <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
        <div class="controls">
            <?php echo $this->formElement($element); ?>   
        </div>
    </div>

    <?php $element = $this->form->get('hide'); ?>
    <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
        <div class="controls">
            <?php echo $this->formElement($element); ?>   
        </div>
    </div>

    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <?php $element = 'newsletter_role'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <select id="<?php echo $element; ?>" name="<?php echo $element; ?>">
                <option></option>
                <?php foreach($this->roles as $role): ?>
                    <option value="<?php echo $role['role_id']; ?>" <?php if($this->entity['newsletter_role']==$role['role_id']): ?>selected="selected"<?php endif; ?>><?php echo $role['role_name']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <?php $element = $this->form->get('newsletter_date_signin'); ?>
    <div class="control-group<?php if(count($element->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element->getName(); ?>"><?php echo $this->formLabel($element); ?></label>
        <div class="controls">
            <?php echo $this->formElement($element); ?>   
        </div>
    </div>
    
    <div class="form-actions" style="padding:0;margin:0;padding:10px;margin-bottom:10px;">
        <button class="btn btn-primary" type="submit">
            <i class="icon-plus icon-white"></i>
            <?php echo $this->translate('Edit'); ?>
        </button>
        <a class="btn" href="<?php echo $this->url($this->module, array('controller'=>$this->controller,'action'=>'index')); ?>">
            <?php echo $this->translate('Back'); ?>
        </a>
    </div>
</form>