<?php
function error_level_tostring($intval, $separator)
{
    $errorlevels = array(
        2047 => 'E_ALL',
        1024 => 'E_USER_NOTICE',
        512 => 'E_USER_WARNING',
        256 => 'E_USER_ERROR',
        128 => 'E_COMPILE_WARNING',
        64 => 'E_COMPILE_ERROR',
        32 => 'E_CORE_WARNING',
        16 => 'E_CORE_ERROR',
        8 => 'E_NOTICE',
        4 => 'E_PARSE',
        2 => 'E_WARNING',
        1 => 'E_ERROR');
    $result = '';
    foreach($errorlevels as $number => $name)
    {
        if (($intval & $number) == $number) {
            $result .= ($result != '' ? $separator : '').$name; }
    }
    return $result;
}
?>

<div class="btn-group" style="text-align:center">
    <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'topic', 'action'=>'new')); ?>"><i class="icon-plus icon-white"></i> page</a>
    <a class="btn" href="<?php echo $this->url('admin',array('controller'=>'project', 'action'=>'new')); ?>"><i class="icon-plus"></i> project</a>
    <a class="btn" href="<?php echo $this->url('admin',array('controller'=>'project', 'action'=>'index')); ?>">Mes projets</a>
</div>

<form style="margin-top: 1em;margin-left:auto;margin-right: auto;" class="form-actions form-horizontal" action="<?php echo $this->url('admin',array('action'=>'index')); ?>" method="post">

    <p style="text-align: center;">
        <textarea id="note" name="note" style="border-radius: 10px;width: 450px;height: 100px;border-color: yellow;background-color: #FFFAAA;padding: 10px;"><?php echo $this->note; ?></textarea>
    </p>
    
    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="btn-group" style="text-align: center;">
        <button class="btn btn-primary" type="submit">
            Save
        </button>
        <a href="#" class="btn">Reset</a>
    </div>

</form>

<div class="well" style="float:left;width:45%;">
<table class="table table-striped">
    <tr>
        <th>Date</th>
        <th>Success</th>
    </tr>
    <?php foreach($this->auths as $auth): ?>
    <tr>
        <td><?php echo date('d/m/Y H:i', $auth['date']); ?></td>
        <td><?php echo ($auth['success'])?'<span class="label label-success">true</span>':'<span class="label label-important">false</span>'; ?></td>
    </tr>
    <?php endforeach; ?>
</table>
</div>

<div class="well" style="margin-left:10px;float:left;width:45%;">
<table class="table table-striped">
    <tr>
        <th>Administrateur</th>
        <td><?php echo $this->layout()->user->username; ?></td>
    </tr>
    <tr>
        <th>Project</th><td><?php echo $this->layout()->project['name'] ?> ( <?php echo round($this->uptime,1); ?> days )</td>
    </tr>
    <tr>
        <th>Last action</th><td><?php echo $this->log ?></td>
    </tr>
    <tr>
        <th><a href="<?php echo $this->url('admin', array('action'=>'index'), null, true); ?>">Topics</a></th><td><?php echo $this->count_topics['COUNT(t.id)']; ?></td>
    </tr>
    <tr>
        <th><a href="<?php echo $this->url('admin', array('action'=>'index'), null, true); ?>">Files</a></th><td><?php echo $this->count ?> ( <?php echo round($this->sizes, 2); ?> ko )</td>
    </tr>
    <tr>
        <th><a href="<?php echo $this->url('admin', array('action'=>'index'), null, true); ?>">Design</a></th><td><?php echo (!empty($this->project['theme']))?$this->project['theme']:'default' ?> ( <?php echo $this->design_count ?> choice(s), <?php echo round($this->design_sizes, 2); ?> ko )</td>
    </tr>
    <tr>
        <th><a href="<?php echo $this->url('admin', array('action'=>'index'), null, true); ?>">Users</a></th><td><?php echo $this->count_users['COUNT(u.id)'] ?></td>
    </tr>
    <tr>
        <th><a href="<?php echo $this->url('admin', array('action'=>'index'), null, true); ?>">Comments</a></th><td><?php echo $this->count_comments['COUNT(c.id)'] ?></td>
    </tr>
    <tr>
        <th>Version</th><td><?php echo $this->version; ?></td>
    </tr>
    <tr>
        <th>Default module</th><td><?php // $ressources = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('resources'); echo $ressources['frontController']['defaultModule'] ?></td>
    </tr>
    <tr>
        <th>Environment</th><td><?php echo getenv('APPLICATION_ENV'); ?></td>
    </tr>
    <tr>
        <th>Driver</th><td><?php echo $this->driver; ?></td>
    </tr>
    <tr>
        <th>Root path</th><td><?php echo dirname($_SERVER['SCRIPT_FILENAME']); ?> ( <?php echo substr(sprintf('%o', fileperms(dirname($_SERVER['SCRIPT_FILENAME']))), -4); ?> )</td>
    </tr>
    <tr>
        <th>Web path</th><td><?php echo dirname(dirname($_SERVER['PHP_SELF'])); ?></td>
    </tr>
    <tr>
        <th>Upload path</th><td><?php echo dirname($_SERVER['SCRIPT_FILENAME']).'/uploads'; ?> ( <?php echo substr(sprintf('%o', fileperms(dirname($_SERVER['SCRIPT_FILENAME']).'/uploads')), -4); ?> )</td>
    </tr>
    <tr>
        <th>Operating system</th><td><?php echo PHP_OS ?></td>
    </tr>
    <tr>
        <th>Web server</th><td><?php echo $_SERVER['SERVER_SOFTWARE'] ?></td>
    </tr>

<?php /* if($ressources['db']['adapter']=="pdo_mysql" and $ressources['db']['params']['host']=="localhost"): ?>
    <tr>
        <th>Mysql version</th><td><?php echo mysql_get_server_info(); ?> <?php echo mysql_get_host_info(); ?></td>
    </tr>
<?php endif; */ ?>

    <tr>
        <th>Uptime</th><td><?php echo exec('uptime'); ?></td>
    </tr>
    <tr>
        <th>User system</th><td><?php echo exec('whoami'); ?></td>
    </tr>
    <tr>
        <th>Ports</th><td><?php echo $_SERVER['SERVER_PORT']; ?></td>
    </tr>
</table>
    <p><a class="btn" href="<?php echo $this->url('admin', array('controller'=>'index','action'=>'info')); ?>">Advanced Informations</a><p>
</div>