<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller' => 'user', 'action' => 'create')); ?>" method="post">
      <fieldset class="control-group">
        <legend>Create user</legend>

        <?php $element = 'username'; ?>
        <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
            <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
            </div>
        </div>

        <?php $element = 'password'; ?>
        <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
            <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
            <div class="controls">
                <input type="password" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
            </div>
        </div>
        
        <?php $element = 'confirmPassword'; ?>
        <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
            <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
            <div class="controls">
                <input type="password" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
            </div>
        </div>
        
        <?php $element = 'email'; ?>
        <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
            <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->form->get($element)->getValue(); ?>">
            </div>
        </div>
        
        <?php $element = 'role'; ?>
        <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
            <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
            <div class="controls">
                <select id="<?php echo $element; ?>" name="<?php echo $element; ?>">
                    <?php foreach($this->roles as $role): ?>
                        <option value="<?php echo $role['role_id']; ?>"><?php echo $role['role_name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="form-actions btn-group">
            <button class="btn btn-primary" type="submit">Create</button>
            <a class="btn" href="<?php echo $this->url('admin', array('controller' => 'user', 'action' => 'index')); ?>">
                Back
            </a>
        </div>

        <?php echo $this->formInput($form->get('csrf')); ?>

    </fieldset>
</form>