<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
        echo '.<br />';
    }
    echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->url('admin', array('controller'=>'product','action'=>'update','id'=>$this->entity['id'])); ?>" method="post" enctype="multipart/form-data">
<fieldset>
<legend>Edit a Product</legend>

    <div class="control-group">
        <label class="control-label" for="topic">Menu</label>
        <div class="controls">
        <select multiple="multiple" name="topics[]">
            <?php foreach($this->topics as $topic): ?>
                <option <?php if($this->entity['topic_id']==$topic['id']): ?>selected="selected"<?php endif; ?> value="<?php echo $topic['id']; ?>">
                    <?php for($i=0;$i<$topic['depth'];$i++): ?> - <?php endfor; ?> <?php echo $topic['name']; ?>
                </option>
            <?php endforeach; ?>
        </select>
        </div>
    </div>


    <?php $element = 'name'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'description'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <textarea type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element ?>"><?php echo $this->entity[$element]; ?></textarea>
        </div>
    </div>

    <?php $element = 'stock'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'weight'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'delay'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'price'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>

    <?php $element = 'discount'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="text" class="input-xlarge" id="<?php echo $element; ?>" name="<?php echo $element; ?>" value="<?php echo $this->entity[$element]; ?>">
        </div>
    </div>


	<?php /* $element = 'file'; ?>
    <div class="control-group<?php if(count($this->form->get($element)->getMessages())>0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="file" name="<?php echo $element; ?>[2]" />
        </div>
    </div>
	<?php */ ?>

    <?php /* if(!empty($this->entity['image_name'])): ?>
    <div class="control-group">
        <label class="control-label" for="<?php echo $element; ?>">Thumb</label>
        <div class="controls">
            <img src="<?php echo $this->basePath($this->entity['image_path'] . 'thumb/' . $this->entity['image_name']); ?>" />
        </div>
    </div>
    <?php endif; */ ?>
    <?php $element = 'file'; ?>
    <div class="control-group<?php if (count($this->form->get($element)->getMessages()) > 0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls" style="border-radius: 10px;border:solid 1px #dedede;padding-left:10px;">
            <?php foreach ($this->files as $file): ?>
                <div style="float:left;">
                    <p><input type="file" name="<?php echo $element; ?>[<?php echo $file['productfile_position']; ?>]" /></p>
                    <p><img src="<?php echo $this->basePath($this->image_path . 'thumb/' . $file['productfile_name']); ?>" /></p>
                </div>
            <?php endforeach; ?>
            <div style="clear:both;"></div>
        </div>
    </div>

    <?php $element = 'file'; ?>
    <div class="control-group<?php if (count($this->form->get($element)->getMessages()) > 0): ?> error<?php endif; ?>">
        <label class="control-label" for="<?php echo $element; ?>"><?php echo $this->formLabel($this->form->get($element)); ?></label>
        <div class="controls">
            <input type="file" name="<?php echo $element; ?>[]" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Parameter</label>
        <div class="controls">
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" <?php if ($this->entity['hide']) echo 'checked="checked"' ?> />
                <?php echo $this->translate('Hide'); ?>
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="comment">
                <input type="checkbox" name="comment" id="comment" <?php if ($this->entity['comment']) echo 'checked="checked"' ?> />
                <?php echo $this->translate('Comment'); ?>
            </label>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="barcode">Barcode</label>
        <div class="controls">
            <?php echo $this->barcode; ?>
        </div>
    </div>

    </fieldset>
    <fieldset>
    <legend>Déclinaisons</legend>

    <?php $title = null; ?>
    
    <?php foreach($this->options as $option): ?>
        <?php
        if(isset($this->entity['options'][$option['sa_id']][$option['sac_id']])) {
            $o[$option['sa_id']]['name'] = $option['sa_name'];
            $o[$option['sa_id']][$option['sac_id']] = $option['name'];
        }
        ?>
        <?php if($title!=$option['sa_name']): ?>
        <?php if($title!=null): ?></div></div><?php endif; ?>
        <?php $title = $option['sa_name']; ?>
        <div class="control-group" style="border:solid 1px #dedede;border-radius: 10px;padding:10px;">
            <label class="control-label" for="<?php echo $element; ?>">
                <?php echo $option['sa_name']; ?>
            </label>
            <div class="controls">
        <?php endif; ?>
            <div>
                <input
                    <?php if(isset($this->poc_ids[$option['sa_id']][$option['sac_id']])) echo 'checked="checked"'; ?>
                    type="checkbox"
                    name="attributes[<?php echo $option['sa_id']; ?>][<?php echo $option['sac_id']; ?>]" 
                    value="1" />
                <?php echo $option['sac_name']; ?>
            </div>
    <?php endforeach; ?>
    <?php if($title!=null): ?></div></div><?php endif; ?>

    </fieldset>
    
    <p><input class="btn" type="submit" value="Générer toutes les déclinaisons" /></p>
    
<fieldset>
<legend>Stocks</legend>

<?php /* foreach($this->entity['options'] as $key=>$options): ?>
    <p><?php echo $o[$key]['name']; ?> :
    <?php foreach($options as $k=>$option): ?>
        <?php echo $o[$key][$k]; ?>
    <?php endforeach; ?>
    </p>
<?php endforeach; ?>
    
<?php
    $options = $this->entity['options'];
    $first_key = key($options);
    echo $first_key;
?>
    <br />
    
    
<?php foreach(current($options) as $key=>$value): ?>
    <p>
    <?php next($options);$next_key = key($options); ?>
    <?php foreach(current($options) as $k=>$v): ?>
        <?php echo $o[$first_key][$key]; ?>-<?php echo $o[$next_key][$k]; ?><br />
    <?php endforeach; ?>
    </p>
<?php endforeach; */ ?>

    <div class="control-group">
        <table>
            <tr>
                <th>Option</th>
                <th>Stock</th>
                <th>Modification du prix</th>
                <th>Montant</th>
                <th><?php echo $this->translate('Price'); ?></th>
            </tr>
            <tr>
                <td>Taille S, Logo Bleu</td>
                <td><input value="<?php echo $this->entity['stock']; ?>" name="aoptions[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Stock" /></td>
                <td>
                    <select><option>Ne change pas</option><option>Egal à</option><option>Augmente de</option><option>Réduire de</option></select>
                </td>
                <td>
                    <input value="<?php echo $this->entity['price']; ?>" name="aoptions[1][choice][]" type="text" name="<?php echo $element; ?>" id="<?php echo $element; ?>" placeholder="Prix" />
                </td>
                <td><?php echo $this->entity['price']; ?></td>
            </tr>
        </table>

    </div>
</fieldset>


    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit"><?php echo $this->translate('Edit'); ?></button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'index')); ?>">
            <?php echo $this->translate('Back'); ?>
        </a>
    </div>
</fieldset>
</form>
