<form action="" method="post">
    <div>
	<input type="text" />
        <button class="btn" type="submit">Search</button>
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Stock</th>
            <th>Prix</th>
            <th>Poids</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->entities as $entity): ?>
        <tr>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'edit', 'id'=>$entity['id'])); ?>"><?php echo $entity['name']; ?></a></td>
            <td><span class="<?php if($entity['stock']==0): ?>text-error<?php endif; ?>"><?php echo $entity['stock']; ?></span></td>
            <td><?php echo $entity['price']; ?></td>
            <td><?php echo $entity['weight']; ?></td>
            <td><?php echo date('d-m-Y H:i',$entity['created']); ?></td>
            <td><?php echo date('d-m-Y H:i',$entity['updated']); ?></td>
            <td><a href="<?php echo $this->url('admin', array('controller'=>'user', 'action'=>'edit', 'id'=>$entity['id'])); ?>"><?php echo $entity['author'] ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="pagination">
  <ul>
    <li><a href="{{ path('_topic_list',{page:previous}) }}">Prev</a></li>
    <li class="active">
      <a href="{{ path('_topic_list',{page:1}) }}">1</a>
    </li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="{{ path('_topic_list',{page:next}) }}">Next</a></li>
  </ul>
</div>

<div class="form-actions">
    <a class="btn btn-primary" href="<?php echo $this->url('admin', array('controller'=>'product','action'=>'new')); ?>">
        <i class="icon-plus icon-white"></i>
        Product
    </a>
    <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'index','action'=>'index')); ?>">
        Back
    </a>
</div>