<!-- Load jQuery -->
<link type="text/css" href="<?php echo $this->basePath('/css/ui-lightness/jquery-ui-1.8.21.custom.css'); ?>" rel="stylesheet" />	

<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-1.7.2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.8.21.custom.min.js'); ?>"></script>

<!-- Load TinyMCE -->
<script type="text/javascript" src="<?php echo $this->basePath('/js/tinymce/jquery.tinymce.min.js') ?>"></script>
<script type="text/javascript">
	$().ready(function() {
            $('.add').click(function() {
                $('textarea.tinymce').tinymce().execCommand('mceInsertContent',false,'<img src="'+this.href+'" />');
                return false;
            });
            $( "#dialog" ).dialog({ autoOpen: false });
            $('#box').click(function() {$('#dialog').dialog('open')});
            $('textarea.tinymce').tinymce({
                // Location of TinyMCE script
                script_url : '<?php echo $this->basePath('/js/tinymce/tinymce.min.js') ?>',
				remove_script_host : false,
				convert_urls : false,
				height : "300",
				width  : "100%",
                menubar: false,
                plugins: [
                    "advlist autolink lists link image charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen ",
                    "insertdatetime media table contextmenu paste textcolor emoticons"
                ],
                toolbar: "undo redo | styleselect fontselect fontsizeselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | code preview fullscreen | searchreplace insertdatetime table print charmap visualblocks anchor removeformat | forecolor backcolor emoticons",
                // General options
                // theme : "modern",
                // plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

                // Theme options
                // theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect,charmap,emotions",
                // theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,print",
                // theme_advanced_resizing : true,
                // theme_advanced_statusbar_location : "none",
                /*
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,
                */
                theme_advanced_statusbar_location : "none",
                // Example content CSS (should be your site CSS)
                // content_css : "css/content.css",

                // Drop lists for link/image/media/template dialogs
                template_external_list_url : "lists/template_list.js",
                external_link_list_url : "lists/link_list.js",
                external_image_list_url : "lists/image_list.js",
                media_external_list_url : "lists/media_list.js",
                schema: "html5",
                // Replace values for the template plugin
                template_replace_values : {
                        username : "Some User",
                        staffid : "991234"
                }
            });
	});
</script>
<!-- /TinyMCE -->

<style>
    ul {
        margin: 0;
        margin-top : 1em;
    }
    li {
        list-style-type:none;
    }
</style>

<?php
    echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
    echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
    echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<div id="dialog">
    <?php if ($this->dir_exists==false): ?>
        <p>Erreur : le dossier image n'existe pas.</p>
    <?php else: ?>
        <?php foreach($this->listFiles as $key=>$image): ?>
            <p><a href="<?php echo $this->basePath('uploads/' . $this->layout()->user->project_id . '/'.$image); ?>" class="add"><?php echo $image ?> <?php echo $this->sizes[$key] ?> ko</a></p>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php
foreach($this->form->getMessages() as $key=>$errors) {
    echo '<div class="alert alert-error">';
    echo '<h4 class="alert-heading">';
    echo $key;
    echo '</h4>';
    foreach($errors as $error) {
        echo $error;
    }
    echo '</div>';
}
?>

<form action="<?php echo $this->url('admin', array('controller'=>'topic','action'=>'create')); ?>" method="post">
<fieldset>

    <div class="control-group input-prepend input-append">
        <span class="add-on" style="font-weight: bold;">Title</span>
        <input type="text" name="name" id="name" value="<?php echo $this->title; ?>" />
        <a class="btn" href="#" id="box"><i class="icon-picture"></i> Insert images</a>
        <a class="btn" href="/admin/myhistories?where=1"><i class="icon-list-alt"></i> Historique</a>
    </div>

    <textarea name="content" id="content" class="control-label tinymce"></textarea>

    <div class="form-actions btn-group" style="margin: 0;border:solid 1px #dedede;border-top: 0;">
        <button class="btn btn-primary" type="submit">
            <?php echo $this->translate('Save'); ?>
        </button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'topic','action'=>'index')); ?>">
            <?php echo $this->translate('List'); ?>
        </a>
    </div>

    <div class="control-group">
        <label class="control-label">Parameter</label>
        <div class="controls">
            <label class="checkbox" for="hide">
                <input type="checkbox" name="hide" id="hide" />
                <?php echo $this->translate('Trash'); ?>
            </label>
        </div>
        <div class="controls">
            <label class="checkbox" for="comment">
                <input type="checkbox" name="comment" id="comment" />
                Comment
            </label>
        </div>

        <div class="controls">
            <label for="topic">Parent</label>
            <select name="parent" id="parent">
                <option value="0" selected="selected" />
                <?php foreach($this->topics as $topic): ?>
                    <option value="<?php echo $topic['id']; ?>"><?php echo $topic['name']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <?php echo $this->formInput($this->form->get('csrf')); ?>

    <div class="form-actions btn-group">
        <button class="btn btn-primary" type="submit">
            <?php echo $this->translate('Save'); ?>
        </button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'topic','action'=>'index')); ?>">
            <?php echo $this->translate('List'); ?>
        </a>
    </div>

</fieldset>
</form>