<!-- Load jQuery -->
<link type="text/css" href="<?php echo $this->basePath('/css/ui-lightness/jquery-ui-1.8.21.custom.css'); ?>" rel="stylesheet" />	

<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-1.7.2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.8.21.custom.min.js'); ?>"></script>

<!-- Load TinyMCE -->
<script type="text/javascript" src="<?php echo $this->basePath('/js/tiny_mce/jquery.tinymce.js') ?>"></script>
<script type="text/javascript">
	$().ready(function() {
            $('.add').click(function() {
                $('textarea.tinymce').tinymce().execCommand('mceInsertContent',false,'<img src="'+this.href+'" />');
                return false;
            });
            $( "#dialog" ).dialog({ autoOpen: false });
            $('#box').click(function() {$('#dialog').dialog('open')});
            $('textarea.tinymce').tinymce({
                // Location of TinyMCE script
                script_url : '<?php echo $this->basePath('/js/tiny_mce/tiny_mce.js') ?>',
				remove_script_host : false,
				convert_urls : false,
				height : "300",
				width  : "100%",

                // General options
                theme : "advanced",
                plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

                // Theme options
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect,charmap,emotions",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,print",
                theme_advanced_resizing : true,
                /*
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,
                */

                // Example content CSS (should be your site CSS)
                // content_css : "css/content.css",

                // Drop lists for link/image/media/template dialogs
                template_external_list_url : "lists/template_list.js",
                external_link_list_url : "lists/link_list.js",
                external_image_list_url : "lists/image_list.js",
                media_external_list_url : "lists/media_list.js",

                // Replace values for the template plugin
                template_replace_values : {
                        username : "Some User",
                        staffid : "991234"
                }
            });
	});
</script>
<form action="<?php echo $this->url('admin', array('controller'=>'comment','action'=>'create')); ?>" method="post" {{ form_enctype(form) }}>
<fieldset>
<legend>New comment</legend>

    <div class="control-group">
        
        <div class="control-group input-prepend input-append">
            <span class="add-on" style="font-weight: bold;">Topic</span>
            <select name="parent" id="parent">
                <option value="0" selected="selected" />
                <?php foreach($this->topics as $topic): ?>
                    <option value="<?php echo $topic['id']; ?>"><?php echo $topic['name']; ?></option>
                <?php endforeach; ?>
            </select>
            <a class="btn" href="#" id="box"><i class="icon-picture"></i> Insert images</a>
            <a class="btn" href="/admin/myhistories?where=1"><i class="icon-list-alt"></i> Historique</a>
        </div>
        
        <textarea name="content" id="content" class="control-label tinymce"></textarea>

    </div>

    <?php echo $this->formInput($form->get('csrf')); ?>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">
            Save
        </button>
        <a class="btn" href="<?php echo $this->url('admin', array('controller'=>'comment','action'=>'index')); ?>">
            List
        </a>
    </div>

</fieldset>
</form>